### ISSUE TITLE
Regarding replication with a partitioned database

### ISSUE THREAD

**Issue by cilvet** [ibm-cloud-docs/Cloudant#10]
Hi! I've been experimenting with cloudant for the last months and I just found out about the new partitioning feature. Is there currently a way to replicate only the documents from a partition? If not, will this feature come at some point?

This could be very useful for my case.

Sorry for posting here, I did not know where to go for this kind of question.

**Comment by lbboe** [comment]
Hello, I apologize for my late reply. I was out of the office for three weeks. I spoke with a developer. There is no way to replicate from one partition, and it most likely will not be a new feature later due to implementation issues.
