### ISSUE TITLE
IBM Cloud Dedicated Cloudant service 

### ISSUE THREAD

**Issue by zebas12** [ibm-cloud-docs/Cloudant#11]

**Comment by lbboe** [comment]
Hello @zebas12 

There is no real version of Cloudant given all the parts of the stack, but you can see what database core version you're using by calling the https://<account>.cloudant.com endpoint. See the following example:

$ acurl https://education.cloudant.com | jq .

You will see a response similar to this one: 

{
  "couchdb": "Welcome",
  "version": "2.1.1",
  "vendor": {
    "name": "IBM Cloudant",
    "version": "8070",
    "variant": "paas"
  },
  "features": [
    "geo",
    "iam",
    "partitioned",
    "pluggable-storage-engines",
    "scheduler"
  ],
  "features_flags": [
    "partitioned"
  ]
}

You can then match the version, in this case, 8070, with the corresponding release notes, https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-release-notes#build-8070-may-2019. Thanks for reaching out. 

Best regards, 
Lora
