### ISSUE TITLE
Custom domain names for cloudant endpoint

### ISSUE THREAD

**Issue by ducklin5** [ibm-cloud-docs/Cloudant#12]
The [docs](https://cloud.ibm.com/docs/services/Cloudant/offerings?topic=cloudant-connecting#endpoints) state that the way to access a cloudant database is through the really long autogenerated enpoints. I've seen some custom domains in some tutorials and I'm wondering if that is a feature that can be turned on, if so how? and will this be added to the docs?

**Comment by lbboe** [comment]
Hello @ducklin5, Thanks for reaching out. This is not a feature in Cloudant.
