### ISSUE TITLE
js typeof not a function

### ISSUE THREAD

**Issue by missinglink** [ibm-cloud-docs/Cloudant#14]
Hi,

Your docs here https://cloud.ibm.com/docs/services/Cloudant/api?topic=cloudant-search describe the javascript `typeof` operator as a function. 

A little pedantic maybe but it's not actually a function 😝 

https://stackoverflow.com/questions/2797517/typeof-is-an-operator-and-a-function

**Comment by lbboe** [comment]
Hello, 

Thanks for sending us your feedback! I updated the sentence to say operator instead of function. You can see it here, https://cloud.ibm.com/docs/services/Cloudant/api?topic=cloudant-search#example-of-failing-to-check-whether-the-index-data-field-exists-. 

Thanks again, 
Lora
