### ISSUE TITLE
Missing Cloudant documentation for the /db/_local/{id} endpoint

### ISSUE THREAD

**Issue by ellablac** [ibm-cloud-docs/Cloudant#16]
The documentation is missing the Cloudant equivalents of **/db/_loca/{id}** and **/db/_local_docs**(CouchDB 2.0) endpoints.

**Comment by lbboe** [comment]
Hello, Thanks for reaching out to us. Cloudant doesn't support the **_local_docs** endpoint. For the **_local/{id}** endpoint, I have added it to our queue of documentation to be written in the future. Thanks again.
