### ISSUE TITLE
"Node.js and IBM Cloudant" & "Liberty for Java and IBM Cloudant" Links are not working.

### ISSUE THREAD

**Issue by imankurpatel000** [ibm-cloud-docs/Cloudant#17]
Go to the following page:
https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-getting-started
Click on the link for "Liberty for Java and IBM Cloudant" OR "Node.js and IBM Cloudant" and you will see that the links are not working.

**Comment by lbboe** [comment]
Thanks for reaching out to report that those links were broken. They're fixed now. Thanks again.
