### ISSUE TITLE
The tutorial on Creating a Cloudant Query results in an error

### ISSUE THREAD

**Issue by jadegraaf** [ibm-cloud-docs/Cloudant#2]
The section on ["Running a query with two fields"](https://github.com/IBM-Bluemix-Docs/Cloudant/blob/master/tutorials/create_query.md), where the sort function is introduced, results in an error on my Bluemix Cloudant instance.

The queries in question are:

```
{
"selector": {
  "lastname": "Brown",
  "location": "New York City, NY"
},
"fields": [
  "firstname",
  "lastname",
  "location"
],
"sort": [
  {
    "lastname": "asc"
  },
  {
    "firstname": "asc"
  }
]  
}
```
and
```
{
  "selector": {
    "lastname": {
      "$eq": "Greene"
    },
    "age": {
      "$gt": 30
    }
  },
  "fields" : [
    "firstname",
    "lastname",
    "age"
  ],
  "sort": [
    {
      "lastname": "asc"
    },
    {
      "firstname": "asc"
    }
  ]   
}
```
I have followed the instruction to the letter, adding the sample documents and the query index to my demo database.

I'm presented with a "Unknown Error: mango_idx :: {no_usable_index,missing_sort_index}" error on query execution.

The error
<img width="1280" alt="schermafbeelding 2017-09-02 om 16 11 16" src="https://user-images.githubusercontent.com/4146844/29996187-1119e5e0-8ffa-11e7-8001-afc2134c3d57.png">

My documents
<img width="1280" alt="schermafbeelding 2017-09-02 om 16 12 47" src="https://user-images.githubusercontent.com/4146844/29996189-14d82e3a-8ffa-11e7-9456-93e191d24fc3.png">

The query index
<img width="767" alt="schermafbeelding 2017-09-02 om 16 51 50" src="https://user-images.githubusercontent.com/4146844/29996460-260d4c8a-8fff-11e7-9b9b-3905cd87da4a.png">

**Comment by jadegraaf** [comment]
As https://stackoverflow.com/a/46056228/8552310 has explained to me, the tutorial doesn't specify that another index has to be made with the firstname and lastname fields. This resolves the problem:

`
{
  "selector": {
    "lastname": "Brown",
    "location": "New York City, NY"
  },
  "fields": [
    "firstname",
    "lastname",
    "location"
  ],
  "sort": [
    {
      "lastname": "asc"
    }
  ]
}
`

**Comment by tonysun83** [comment]
@jadegraaf : We will need to update the documentation on the bluemix site. I just wanted to clarify the reason that another index needed to be created. When a sort is specified for an index, the fields specified by the sort must be a prefix of the defined fields at index definition time. So if you sort based on fields ```a``` and ```b``` and ```c``` in that order, there has to be a index defined 
```
{
  "index": {
    "fields": [
      "a",
      "b",
      "c"
    ]
  },
  "type": "json"
}
```
In the stackoverflow reply, creating the index with ```lastname``` and ```firstname``` in order fits this requirement and hence resolves the problem.

**Comment by jadegraaf** [comment]
Thanks for the response and explanation @tonysun83! I'm glad that this problem will be resolved.

**Comment by lbboe** [comment]
Closing. The problem was addressed.
