### ISSUE TITLE
Global Query Definition is not mentioned

### ISSUE THREAD

**Issue by ramkinavy** [ibm-cloud-docs/Cloudant#21]
Global Query Definition is not mentioned. This is important metric for deciding the capacity planning

**Comment by lbboe** [comment]
@ramkinavy Thanks for reaching out! Global queries are discussed in this section, https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-ibm-cloud-public#event-types. Let us know if you need anything else.
