### ISSUE TITLE
Event is not getting with Node Js 

### ISSUE THREAD

**Issue by Manoj-C4C** [ibm-cloud-docs/Cloudant#23]
Hi cloudant team,

I am using cloudant db as a service with nodejs server. 
I am unable to get an event in server side while any update operation performed on cloudant.

can you help us to track an event while update any document properties value through other application.

**Comment by lbboe** [comment]
Hello Manoj, Thank you for reaching out. Please check out the "_changes_feed" section in the documentation. If you are still having issues, please contact Cloudant support. 

 https://cloud.ibm.com/docs/services/Cloudant/api?topic=cloudant-databases#get-changes

Thank you, 
Lora
