### ISSUE TITLE
Suggested note to add in the docs.

### ISSUE THREAD

**Issue by libesz** [ibm-cloud-docs/Cloudant#26]
There is an undocumented network behavior, identified when troubleshooted customer problem after deploying CouchDB, based on this doc: https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-deploy-couchdb-cluster
When CouchDB is installed, it installs certain `NetworkPolicy` objects in the specified Kubernetes namespace. It basically locks down the entire ingress traffic except which targets CouchDB. Customer wanted to install database client application in the same namespace and so it couldn't be exposed due to the deny-all `NetworkPolicy`. This is anyway not recommended in production, but it is not mentioned in the documentation. I think it is worth to add.

**Comment by michaelbreslin** [comment]
@willholley @welshDoug comments on ^^ suggestion for the docs? 

(still a lot more to add to docs on CouchDB story of course)

**Comment by willholley** [comment]
@michaelbreslin @libesz this was fixed with version `1.0.7` of the operator. There is still a NetworkPolicy deployed, but it targets only the CouchDB pods.

**Comment by lbboe** [comment]
Thanks everyone!
