### ISSUE TITLE
_replicator database not found

### ISSUE THREAD

**Issue by CatherineCao2016** [ibm-cloud-docs/Cloudant#3]
Hi, I am trying to create a replication using the code below:

from cloudant.client import Cloudant
from cloudant.replicator import Replicator

client = Cloudant(username, password, url = cloudant_url, connect=True)

session = client.session()
    
retaildemo_dept = client.create_database('retaildemo-dept')

rep_ins = Replicator(client)

dept = Replicator.create_replication(rep_ins, source='https://redbookid.cloudant.com/retaildemo-dept', target=cloudant_url + "/retaildemo-dept", repl_id = 'retaildemo-dept', user_ctx = user_ctx)

but get the error as "there is not _replicator database in the instance. The code works only if a replication has be manually created through the dashboard(since _replicator will be automatically created that way). 

Can someone help? Thanks!

**Comment by nickva** [comment]
Hi @CatherineCao2016,

I think you just need to create a _replicator database in your account first. Give it a try and see if it works.

**Comment by lbboe** [comment]
Closing. The question was answered.
