### ISSUE TITLE
Minor typo: Persistant

### ISSUE THREAD

**Issue by matrober-uk** [ibm-cloud-docs/Cloudant#30]
Hi folks - I happened to be reading your [docs about storage](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-configure-couchdb-cluster#couchdb-storage) and spotted a minor spelling mistake - I believe it should be "persistent" (with an "e") rather than "persistant".

From a quick search of your docs that page looks to be the only one with the "a" spelling.

**Comment by feejaydee** [comment]
PR raised here for the typo: https://github.com/ibm-cloud-docs/Cloudant/pull/31

**Comment by lbboe** [comment]
Thank you for telling us about the typo. You can see it's fixed here, https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-configure-couchdb-cluster#couchdb-storage.

**Comment by matrober-uk** [comment]
thanks @lbboe !
