### ISSUE TITLE
Failed Login on Node-RED

### ISSUE THREAD

**Issue by Jamesgiggs** [ibm-cloud-docs/Cloudant#33]
How do I fix failed login from Node-RED?

**Comment by Jamesgiggs** [comment]
![node red](https://user-images.githubusercontent.com/57169141/100547724-9011b800-3268-11eb-90e9-088bfe195409.PNG)

**Comment by lbboe** [comment]
Hi James, If you have an issue with your account, please open a case via https://cloud.ibm.com/unifiedsupport/cases/add.
Thanks for reaching out.
