### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by revanth844** [ibm-cloud-docs/Cloudant#34]
We are already trying replication job, which is super slow, with DB-size of ~50GB (takes 24 hours).
I'm looking for different ways of quickly creating cloudant backup, may be into a file. 

URLs at the end of this page are broken. Please review and fix.
[https://github.com/ibm-cloud-docs/Cloudant/blob/master/tutorials/create_backup.md](https://github.com/ibm-cloud-docs/Cloudant/blob/master/tutorials/create_backup.md)

**Comment by lbboe** [comment]
Hello, Thank you for reaching out. We always appreciate your feedback. 

All the links work for me. I tried them on Chrome, Firefox, and Safari. I'm not sure what's happening. Sometimes deleting your cookies helps. I have pasted the direct links for you here: 

https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-disaster-recovery-and-backup#disaster-recovery-and-backup

https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-configuring-ibm-cloudant-for-cross-region-disaster-recovery#configuring-ibm-cloudant-for-cross-region-disaster-recovery

https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-ibm-cloudant-backup-and-recovery#ibm-cloudant-backup-and-recovery

If you need more help with your backup, you can email support at support@cloudant.com. Please let me know if you have any other issues.
