### ISSUE TITLE
Broken link "Advantages and disadvantages of the two access control mechanisms."

### ISSUE THREAD

**Issue by TalAviel** [ibm-cloud-docs/Cloudant#35]
A broken link on https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-faq-authenticating-cloudant -

["Advantages and disadvantages of the two access control mechanisms."](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-ibm-cloud-identity-and-access-management-iam-#advantages-and-disadvantages-of-the-two-access-control-mechanisms)

**Comment by lbboe** [comment]
Thank you for letting us know. The link is fixed now. Thanks again.
