### ISSUE TITLE
Couch DB 3.x in comparison chart

### ISSUE THREAD

**Issue by egriff38** [ibm-cloud-docs/Cloudant#36]
Hello. CouchDB 3.0 has been out for [almost a year now](https://blog.couchdb.org/2020/02/26/3-0/). The comparison page for Cloudant [here](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-comparison-of-ibm-cloudant-and-couchdb-api-endpoints&_ga=2.4908019.1165320250.1604321683-1614077795.1594908456#comparison-of-cloudant-and-couchdb-api-endpoints) does not show the comparisons against Couch 3.x. I was interested to know if the Cloudant platform would be getting the same feature set CouchDB 3 has, specifically the upgraded spidermonkey v60 runtime. I haven't been able to find any documentation on the subject. Thanks in advance!

**Comment by lbboe** [comment]
Hi, Thanks for reaching out. I will update the comparison page as soon as possible. Also, Spidermonkey v60 is included with the IBM Cloudant Standard on Transaction Engine plan. 

Thanks again, 
Lora

**Comment by egriff38** [comment]
Hi Lora, thanks for the response. Do you know if there are plans to upgrade for the standard Cloudant?

**Comment by lbboe** [comment]
Hello, I asked a developer. He suggested that you open a support ticket, and a developer will respond. 

Thanks again, 
Lora
