### ISSUE TITLE
Link to missing document in https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-connecting

### ISSUE THREAD

**Issue by IzhakJakov** [ibm-cloud-docs/Cloudant#39]
### The link "API keys" 
![image](https://user-images.githubusercontent.com/18270061/124602344-bd45ca80-de36-11eb-9db0-8cf476fafb3d.png)
</br>
### leads to https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-api-keys which is missing
<img src="https://user-images.githubusercontent.com/18270061/124602556-fa11c180-de36-11eb-8362-9b1e7285ca1b.png" width="512" />

**Comment by lbboe** [comment]
Hi Izhak, I fixed the link. Thanks for letting us know. 

Regards, 
Lora
