### ISSUE TITLE
CouchDB Operator provided by IBM not getting installed on openshift 4.8

### ISSUE THREAD

**Issue by anuj812** [ibm-cloud-docs/Cloudant#40]
CouchDB Operator provided by IBM not getting installed on openshift 4.8

Exception: No configmap found: configmap "c-couchdb-m" (from "${SERVICENAME}") cannot be read. configmap "c-couchdb" (from "c-${ID}") cannot be read.

**Comment by lbboe** [comment]
Hello, Thank you for reaching out. This is not a support repo. You can email support at support@cloudant.com.

Thanks again, 
Lora
