### ISSUE TITLE
links broken

### ISSUE THREAD

**Issue by Neo1975** [ibm-cloud-docs/Cloudant#41]
At Page https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-design-document-management

IBM® Cloudant® for IBM Cloud's search indexes and MapReduce views

**search indexes** and **MapReduce views**

point to a not exist page.

**Comment by lbboe** [comment]
Hello, Thank you for taking the time to report this issue. I fixed both links in the document. 

Thanks again, 
Lora
