### ISSUE TITLE
Documentation : 

### ISSUE THREAD

**Issue by revanth844** [ibm-cloud-docs/Cloudant#43]
In the following page, the text says `PUT` while the snippets illustrate `POST`.
Please adjust either to match other.
https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-update-docs&code=curl

<img width="1334" alt="Screenshot 2022-09-12 at 09 49 22" src="https://user-images.githubusercontent.com/5076245/189573456-feb42aa8-6e6e-4937-805d-aed3f1d66fa1.png">

I've used `PUT` to both CREATE/UPDATE cloudant documents.

**Comment by lbboe** [comment]
Hello, Thank you for taking the time to let us know about this issue. I have changed the text. You can see it here, https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-update-docs.

Thanks again, 
Lora
