### ISSUE TITLE
DPO sentence links to W3 IBM Intranet

### ISSUE THREAD

**Issue by coldsync** [ibm-cloud-docs/Cloudant#44]
The link is not accessible outside IBMers.
IBM Cloudant is accepting the Right to be forgotten requests through the [IBM Data Privacy Office (DPO)](http://w3.ibm.com/ibm/privacy/index.html).

**Comment by lbboe** [comment]
Hello, I updated the link. You can see it here, https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-general-data-protection-regulation-gdpr-#when-is-a-deleted-document-removed-.

Thanks for reporting the issue. We appreciate you taking the time. 

Thanks again, 
Lora
