### ISSUE TITLE
Version for Windows ?

### ISSUE THREAD

**Issue by ronanb3** [ibm-cloud-docs/Cloudant#5]
This document (Cloudant/guides/acurl.md) is for Unix Apple users. Could we have a version for windows users ?
This is true for many documents.
Let me know if I can help on this and how.

**Comment by lbboe** [comment]
Hello, 

Thank you for contacting us. It's helpful to get your feedback. For the acurl alias, it is a handy tool. However, you can run curl commands on Windows by specifying your user name and password. I added a note to the topic for Windows users. 

Thanks again, 
Lora
