### ISSUE TITLE
Cloudant/tutorials/create_query.md : "Running a query with two fields" not working

### ISSUE THREAD

**Issue by ronanb3** [ibm-cloud-docs/Cloudant#6]
In the document Cloudant/tutorials/create_query.md, the part "Running a query with two fields" is not working.
I have the error message : "Error running query. Reason: (no_usable_index) No index exists for this sort, try indexing by the sort fields."
There is no index with "firstname" in it, that may be the origin of his error.

**Comment by lbboe** [comment]
The Cloudant Query tutorial has been changed so that "Running a query with two fields" works.
